codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false

# Paths to ignore from coverage reports
# These patterns exclude entire directories from coverage analysis
ignore:
  - "test/**"
  - "benchmark/**"
  - "build/**"
  - "docs/**"
  - "**/*.md"

# Define coverage components for better organization
component_management:
  default_rules:
    statuses:
      - type: project
      - type: patch
  individual_components:
    - component_id: library
      name: Library Code
      paths:
        - src/**
        - include/**

flags:
  unittests:
    paths:
      - src/
      - include/
