codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false

# Paths to ignore from coverage reports
ignore:
  - "test/**/*"
  - "benchmark/**/*"
  - "build/_deps/**/*"
  - "**/*.md"

flags:
  unittests:
    paths:
      - src/
      - include/
