homepage: "https://github.com/jimhester/simdcsv"
language: c++
primary_contact: "jim.hester@gmail.com"
main_repo: "https://github.com/jimhester/simdcsv"
fuzzing_engines: [libfuzzer, afl, honggfuzz]
sanitizers: [address, undefined, memory]
architectures: [x86_64]
